from flask import Flask, jsonify, request, Response
import requests

app = Flask(__name__, template_folder='../templates')

# ==================== HEADERS UNTUK STALKER ====================
def get_stalker_headers(mac):
    return {
        "User-Agent": "Mozilla/5.0 (QtEmbedded; U; Linux; C) AppleWebKit/533.3 (KHTML, like Gecko) MAG200 stbapp ver: 2 rev: 250 Safari/533.3",
        "X-User-Agent": "Model: MAG200; Link: Ethernet",
        "Cookie": f"mac={mac}; stb_lang=en; timezone=Europe/London",
        "Accept": "*/*",
    }

# ==================== PROXY REQUEST KE PORTAL ====================
def proxy_portal_request(portal, action, mac, extra_params=None):
    if extra_params is None:
        extra_params = {}
    
    url = f"{portal.rstrip('/')}/portal.php"
    params = {
        "action": action,
        "JsHttpRequest": "1-xml",
        **extra_params
    }
    
    headers = get_stalker_headers(mac)
    
    try:
        r = requests.get(url, params=params, headers=headers, timeout=15)
        if r.status_code == 200:
            return r.json()
        else:
            return {"status": "error", "message": f"HTTP {r.status_code}"}
    except Exception as e:
        return {"status": "error", "message": str(e)}

# ==================== ROUTE UTAMA ====================
@app.route('/')
def home():
    return render_template('index.html')

# ==========================================
# 1. TEST KODE IPTV
# ==========================================
@app.route('/test', methods=['POST'])
def test_code():
    mode = request.form.get('mode')
    server = request.form.get('server', '').strip().rstrip('/')
    
    # XTREAM CODES (tetap pakai server request)
    if mode == 'xtream':
        username = request.form.get('user', '').strip()
        password = request.form.get('pass', '').strip()
        if not username or not password:
            return jsonify({"status": "error", "message": "Username dan Password wajib diisi"}), 400
            
        test_url = f"{server}/player_api.php?username={username}&password={password}"
        try:
            response = requests.get(test_url, timeout=8)
            if response.status_code == 200:
                data = response.json()
                user_info = data.get('user_info', {})
                if user_info.get('auth') == 1 and user_info.get('status') == 'Active':
                    return jsonify({
                        "status": "success",
                        "message": f"✅ VALID | Exp: {user_info.get('exp_date')} | Max Conn: {user_info.get('max_connections')}"
                    })
                else:
                    return jsonify({"status": "failed", "message": "Kode tidak aktif"})
            else:
                return jsonify({"status": "error", "message": f"HTTP {response.status_code}"})
        except Exception as e:
            return jsonify({"status": "error", "message": str(e)})

    # MAC PORTAL (PAKAI PROXY)
    elif mode == 'mac':
        mac = request.form.get('mac_address', '').strip().upper()
        if not mac:
            return jsonify({"status": "error", "message": "MAC Address wajib diisi"}), 400
            
        # Handshake via proxy
        result = proxy_portal_request(server, "handshake", mac, {"type": "stb"})
        
        if result.get("status") != "error":
            return jsonify({
                "status": "success",
                "message": f"✅ MAC Portal berhasil dihubungi! (Handshake OK)"
            })
        else:
            return jsonify(result)

    # RAW URL
    elif mode == 'url':
        try:
            res = requests.head(server, timeout=8, allow_redirects=True)
            if res.status_code == 200:
                return jsonify({"status": "success", "message": "✅ URL AKTIF"})
            else:
                return jsonify({"status": "failed", "message": f"HTTP {res.status_code}"})
        except Exception as e:
            return jsonify({"status": "error", "message": str(e)})

    return jsonify({"status": "error", "message": "Mode tidak dikenal"}), 400


# ==========================================
# 2. CONVERT KE M3U (bisa dikembangkan nanti)
# ==========================================
@app.route('/convert', methods=['POST'])
def convert_m3u():
    # ... (kode convert kamu bisa dibiarkan dulu atau dikembangkan)
    # Untuk MAC, nanti kita arahkan juga lewat proxy
    mode = request.form.get('mode')
    server = request.form.get('server', '').strip().rstrip('/')
    
    m3u_content = "#EXTM3U\n# Generated by IPTV Ultimate Tool\n"
    
    if mode == 'mac':
        mac = request.form.get('mac_address', '').strip()
        # Contoh sederhana dulu
        m3u_content += f"#EXTINF:-1,Test Channel\n{server}/portal.php?type=stb&action=get_ordered_list&mac={mac}\n"
        filename = "mac_playlist.m3u"
    else:
        filename = "playlist.m3u"
    
    return Response(
        m3u_content,
        mimetype="audio/x-mpegurl",
        headers={"Content-disposition": f"attachment; filename={filename}"}
    )
